### ISSUE TITLE
Problem on the crafts with the essences

### ISSUE THREAD

**Issue by R-0ne** [TechNolaByte/Mystical-Agriculture#1]
hi, there is a problem in the file essence_crafting.lua : some recipe is not good for example the dirt, it is named mystical_agriculture: dirt_essence, while it was recorded under mystical_agriculture: dirt_item_essence

So, there are no crafts in game.

**Comment by MidnightPhantom** [comment]
I have done this for dye please wait till the crafting recipes are corrected.

**Comment by TechNolaByte** [comment]
I have fixed the naming issue.
