### ISSUE TITLE
Missing prosperity ore and inferium ore

### ISSUE THREAD

**Issue by AFCMS** [TechNolaByte/Mystical-Agriculture#2]
It is important to have these block : it isn't possible now to use this mod in survival

**Comment by MidnightPhantom** [comment]
the maintainer seems to be on vacation so I will try forking and adding the ores and crafting recipes soon enough.

**Comment by TechNolaByte** [comment]
Yeah, younger me was too afraid to touch world-gen. Modern me is too busy to touch Minetest.
Pretty sure this isn't an issue though, cause, if I recall correctly, prosperity shards and inferium essence can both be crafted (though, this is isn't ideal cause ores are better... but technically still survival possible)?

**Comment by TechNolaByte** [comment]
Indeed, prosperity and inferium can be crafted. Inferium can be grown aswell.

**Comment by TechNolaByte** [comment]
The ores have been added.
