### ISSUE TITLE
Harvest Crystal doesn't work

### ISSUE THREAD

**Issue by beepbopbeepboop** [TechNolaByte/Mystical-Agriculture#7]
One is supposed to grow on Harvest Crystal, but nothing grows on it.  I can grow on hoed wet dirt, and once it is grown, dig the dirt out and put in a crystal, and then the crystal will then harvest it.

**Comment by beepbopbeepboop** [comment]
My best guess is something like this.  You'd have to consider if  you want crops on the harvest crystal directly, or merely under the soil.

`--- ./functions.lua.~1~	2024-03-03 10:24:30.000000000 -0800
+++ ./functions.lua	2024-03-04 11:47:56.000000000 -0800
@@ -79,7 +79,9 @@ mystical_agriculture.register_ore_crop =
 			interval = 3,
 			chance = 3,
 			action = function(pos, node)
-				if minetest.get_node({x=pos.x, y=pos.y-1, z=pos.z}).name == "mystical_agriculture:growth_crystal" then
+			        local n = minetest.get_node({x=pos.x, y=pos.y-1, z=pos.z}).name
+				if n == "mystical_agriculture:growth_crystal"
+					or n == "mystical_agriculture:harvest_crystal" then
 					minetest.set_node(pos, {name = "mystical_agriculture:"..id.."step_"..(n+1)})
 				end
 			end
@@ -132,7 +134,8 @@ mystical_agriculture.register_ore_crop =
 		interval = 1,
 		chance = 1,
 		action = function(pos, node)
-			if minetest.get_node({x=pos.x, y=pos.y-1, z=pos.z}).name == "mystical_agriculture:harvest_crystal" then
+			if minetest.get_node({x=pos.x, y=pos.y-1, z=pos.z}).name == "mystical_agriculture:harvest_crystal"
+			   or minetest.get_node({x=pos.x, y=pos.y-2, z=pos.z}).name == "mystical_agriculture:harvest_crystal" then
 				harvest(pos, node)
 			end
 		end
--------------
`

**Comment by TechNolaByte** [comment]
Good notice. Harvest crystals are supposed to go under the soil/growth-crystal, but that was actually broken. Now they can go in either spot.
