### ISSUE TITLE
group ice

### ISSUE THREAD

**Issue by beepbopbeepboop** [TechNolaByte/Mystical-Agriculture#8]
In default, there is no group ice, only default:ice. This breaks the recipe for ice seeds. Either one has to make default:ice group ice, or one has to use default:ice when group:ice is empty.

**Comment by beepbopbeepboop** [comment]
This can be fixed by adding:

  minetest.registered_nodes["default:ice"]["groups"]["ice"]=1

in multiuse_essences.lua before line 3.

**Comment by TechNolaByte** [comment]
Thanks for the suggestion!
